-- MySQL Script generated by MySQL Workbench
-- Wed Dec 15 15:05:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `idContract` INT NOT NULL,
  `idAdmin` INT NOT NULL,
  `idTransportator` INT NULL,
  `idClient` INT NULL,
  `locIncarcare` VARCHAR(45) NULL,
  `locDescarcare` VARCHAR(45) NULL,
  `tarif` INT NULL,
  PRIMARY KEY (`idContract`),
  INDEX `fk_Contract_Admin1_idx` (`idAdmin` ASC) VISIBLE,
  CONSTRAINT `fk_Contract_Admin1`
    FOREIGN KEY (`idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comanda` (
  `idComanda` INT NOT NULL,
  `idContract` INT NOT NULL,
  PRIMARY KEY (`idComanda`, `idContract`),
  INDEX `fk_Comanda_Contract1_idx` (`idContract` ASC) VISIBLE,
  CONSTRAINT `fk_Comanda_Contract1`
    FOREIGN KEY (`idContract`)
    REFERENCES `mydb`.`Contract` (`idContract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `parola` VARCHAR(45) NULL,
  `telefon` INT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Camion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Camion` (
  `idCamion` INT NOT NULL,
  `idComanda` INT NOT NULL,
  `idContract` INT NOT NULL,
  PRIMARY KEY (`idCamion`, `idComanda`, `idContract`),
  INDEX `fk_Camion_Comanda1_idx` (`idComanda` ASC, `idContract` ASC) VISIBLE,
  CONSTRAINT `fk_Camion_Comanda1`
    FOREIGN KEY (`idComanda` , `idContract`)
    REFERENCES `mydb`.`Comanda` (`idComanda` , `idContract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transportator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transportator` (
  `idTransportator` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefon` INT NULL,
  `parola` VARCHAR(45) NULL,
  PRIMARY KEY (`idTransportator`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Oferta` (
  `idOferta` INT NOT NULL,
  `telefonTransportator` INT NULL,
  `emailTransportator` VARCHAR(45) NULL,
  `dataPlecare` DATE NULL,
  `dataSosire` DATE NULL,
  `locPlecare` VARCHAR(45) NULL,
  `locSosire` VARCHAR(45) NULL,
  `pretKmGol` INT NULL,
  `pretKmPlin` INT NULL,
  `Transportator_idTransportator` INT NOT NULL,
  `idAdmin` INT NOT NULL,
  PRIMARY KEY (`idOferta`, `Transportator_idTransportator`, `idAdmin`),
  INDEX `fk_Oferta_Transportator1_idx` (`Transportator_idTransportator` ASC) VISIBLE,
  INDEX `fk_Oferta_Admin1_idx` (`idAdmin` ASC) VISIBLE,
  CONSTRAINT `fk_Oferta_Transportator1`
    FOREIGN KEY (`Transportator_idTransportator`)
    REFERENCES `mydb`.`Transportator` (`idTransportator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oferta_Admin1`
    FOREIGN KEY (`idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cerere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cerere` (
  `idCerere` INT NOT NULL,
  `telefonClient` VARCHAR(45) NULL,
  `emailClient` VARCHAR(45) NULL,
  `locPlecare` VARCHAR(45) NULL,
  `dataPlecare` DATE NULL,
  `locSosire` VARCHAR(45) NULL,
  `dataSosire` DATE NULL,
  `Client_idClient` INT NOT NULL,
  `buget` INT NULL,
  `Admin_idAdmin` INT NOT NULL,
  PRIMARY KEY (`idCerere`, `Client_idClient`, `Admin_idAdmin`),
  INDEX `fk_Cerere_Client_idx` (`Client_idClient` ASC) VISIBLE,
  INDEX `fk_Cerere_Admin1_idx` (`Admin_idAdmin` ASC) VISIBLE,
  CONSTRAINT `fk_Cerere_Client`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cerere_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
